name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '*/1 * * * *'
    
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.'
          close-issue-message: "Closing as stale. Please reopen if you'd like to work on this further"
          close-pr-message: "Closing as stale. Please reopen if you'd like to work on this further"
          days-before-issue-stale: 15
          days-before-issue-close: 15
          days-before-pr-close: 0
          days-before-pr-stale: 0
          any-of-labels: 'awaiting response'
          stale-pr-label: 'Stalled'
          stale-issue-label: "Stalled"

